### ISSUE TITLE
Failed to import antd-table-infinity in a meteor project

### ISSUE THREAD

**Issue by yuri3** [Leonard-Li777/antd-table-infinity#2]
Hi Leonard, I've recently found out this lib (antd-table-infinity), and tried to use it in the meteor project,
but got errors, when try just import (import { InfinityTable } from 'antd-table-infinity'), if you will have some time can you please check it? To quickly check please create a simple meteor project (meteor create --react new-react-app) after you install Meteor, here is the link for the info => (https://www.meteor.com/install)
<img width="430" alt="screen shot 2018-11-14 at 8 23 55 am" src="https://user-images.githubusercontent.com/19604939/48464044-b9c52700-e7e6-11e8-9f57-cdc364769cc1.png">
Thanks.

**Comment by Leonard-Li777** [comment]
Are you try antd-table-infinity@0.0.11 ?
I updated it in yesterday

**Comment by yuri3** [comment]
Hi, yes I’ve tried, got the same errors:(

**Comment by Leonard-Li777** [comment]
try import { InfinityTable } from 'antd-table-infinity/dist'

**Comment by yuri3** [comment]
Hi Leonard, yes, I also tried that, and project runs, but shows another errors again and again like loop.
<img width="423" alt="screen shot 2018-11-15 at 8 34 51 am" src="https://user-images.githubusercontent.com/19604939/48534793-dda16f00-e8b1-11e8-84a4-211ab248b112.png">
if you will have some time, please create a simple meteor project and try to import to see. 
Thanks.

**Comment by yuri3** [comment]
Hi Leonard thanks a lot, it works, but now in the console show ups these warnings
<img width="325" alt="screen shot 2018-11-19 at 8 49 25 am" src="https://user-images.githubusercontent.com/19604939/48690695-481b1d80-ebd8-11e8-933d-2d0dc5227434.png">
<img width="335" alt="screen shot 2018-11-19 at 8 49 39 am" src="https://user-images.githubusercontent.com/19604939/48690709-523d1c00-ebd8-11e8-8e59-601260b60a86.png">
please check that. Thanks.

**Comment by Leonard-Li777** [comment]
columns type is array!
fixed it in antd-table-infinity@0.0.13

const columns = [
  {
    title: 'index',
    dataIndex: 'index',
    render: text => text,
    width: 50,
  },
  {
    title: 'Name',
    dataIndex: 'name',
    width: 100,
  },
  {
    title: 'Age',
    width: 50,
    dataIndex: 'age',
  },
  {
    title: 'Address',
    width: 200,
    dataIndex: 'address',
  },
];

**Comment by yuri3** [comment]
Hi Leonard, thanks a lot, all works.
